### ISSUE TITLE
[Suggestion] Compatibility with Origins datapacks

### ISSUE THREAD

**Issue by JumperREDACTED** [KosmX/emotes#104]
It would be really cool if we could have custom emotes as a part of Origins datapacks and have them be triggered using an action. Or maybe even a power type that replaces regular walking/swimming etc. animations with custom ones packed in the datapack.

I understand this would be a relatively big undertaking and mostly unrelated to the mod itself, so it's understandable if you don't want to bother. Just thought it would be cool, since it's one of the main things I feel custom origins lack and this mod already has most of the code necessary.

**Comment by KosmX** [comment]
Maybe after the 2.1 server-side update

**Comment by KosmX** [comment]
With 2.2 server-side commands, it is possible to play emotes from datapack functions.   
but that should be implemented in the datapack.  

Or if it is a mod, it can implement the server-side API (can be used from modded and spigot server)
