### ISSUE TITLE
Crash while loading the game with Better End mod

### ISSUE THREAD

**Issue by adriancpp** [KosmX/emotes#111]
Crash report in the attached file

I reported issue on betterEnd repo, but author replied that crash is provided by Emotecraft
https://github.com/paulevsGitch/BetterEnd/issues/234

Better End mod -> https://www.curseforge.com/minecraft/mc-mods/betterend
better end version - better-end-0.10.2-pre
emotecraft version - emotecraft-for-MC1.17-2.0.7-fabric 

[crash-2021-07-10_08.57.12-client.txt](https://github.com/KosmX/emotes/files/6796757/crash-2021-07-10_08.57.12-client.txt)

**Comment by KosmX** [comment]
Apparently the same issue has been reported:  
[KosmX/bendy-lib - ModelParts with no cuboids cause IndexOutOfBoundsException #17](https://github.com/KosmX/bendy-lib/issues/17)  
I'll check and update

**Comment by KosmX** [comment]
Updated bendy-lib in Emotecraft 2.0.8 Fabric 1.17
