### ISSUE TITLE
[BUG] Minecraft crashes when trying to export an emote to .json or .emotecraft binary

### ISSUE THREAD

**Issue by Disguys** [KosmX/emotes#122]
Minecraft crashes when trying to export an emote to .json or .emotecraft binary.
Version EmoteCraft: 2.1 Snapshot 1
OS: Windows 10
Log crash:
with the help .json - https://gist.githubusercontent.com/natanfudge/82d8f6a506fcfe43531ee64976baf94a/raw/206d90401c39d59af04cfd38459ddbe07025c6fb/crash.txt
with the help .emotecraft -https://gist.githubusercontent.com/natanfudge/cc7e03a26df7901904dc170db8b3ab23/raw/9a05167feca932fbc2ccbeaee720a474c5afe257/crash.txt

**Comment by KosmX** [comment]
It couldn't save a file `<3.emotecraft`. This file name is invalid...
I'll find a way to avoid it

**Comment by KosmX** [comment]
https://github.com/KosmX/emotes/blob/03b86f4b165c5206fcc6cd18c6a8870b11409de1/emotesMain/src/main/java/io/github/kosmx/emotes/main/screen/ExportMenu.java#L58

**Comment by KosmX** [comment]
Avoiding invalid characters in SNAPSHOT 2
