### ISSUE TITLE
[BUG] Emotecraft-2.1-SNAPSHOT-2

### ISSUE THREAD

**Issue by Disguys** [KosmX/emotes#124]
When trying to export emote to json, the game also crashes, the export button to .emotecraft does not work at all, and for some reason the encoding of all the current emotions that I had installed has gone bad.
Crash log - https://gist.githubusercontent.com/natanfudge/0845563c270e43b8f573a7df1d775e18/raw/9f0742531c69716e40744e4ace5fead51b48e866/crash.txt
![image](https://user-images.githubusercontent.com/60795989/127317012-263309ab-b57c-462b-8683-1cbe827de72f.png)

**Comment by KosmX** [comment]
again, I'll look deeper into this

**Comment by KosmX** [comment]
https://github.com/KosmX/emotes/blob/f720b52f3e8b4d28d9adfd4bde9269eb2464d415/emotesMain/src/main/java/io/github/kosmx/emotes/main/screen/ExportMenu.java#L71

**Comment by KosmX** [comment]
Currently, there is NO feedback if the export was successful.
If you export to binary, it should create a folder in emotes folder, with the name `emotecraft_export`
Please check binary export again!

**Comment by KosmX** [comment]
- fixed encoding in JSON
- fixed crash on icon export
- added toast notification on success export
