### ISSUE TITLE
java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer

### ISSUE THREAD

**Issue by ProsperCraft** [KosmX/emotes#139]
After updating to Forge - 36.2.2 and updating all of my other mods for TownCraft TWO I get this crash on load.

https://gist.github.com/ProsperCraft/436194eeb70efe78dc155435ee1c1da6

**Comment by KosmX** [comment]
Some method signatures have changed after Java1.8 in ByteBuffer.

Using Java 11 or 16 may solve the issue,
this bug is only Emotecraft, **do not** report it on other issue-trackers.
