### ISSUE TITLE
Enhancement: Server Emotes Whitelist

### ISSUE THREAD

**Issue by CamperSamu** [KosmX/emotes#144]
A way to allow only certain emotes from a list given from the server

### Why is this useful?
Not every user wants the "Fap" emote on his server (or wants to limit the usable emotes)

**Comment by KosmX** [comment]
Understood. 
Expect this feature in the snapshot versions soon.

**Comment by KosmX** [comment]
I'm not sure if I want to include a feature like that in the core mod. But it is possible from the server-side API
(on Fabric/Forge/Spigot servers)
