### ISSUE TITLE
Plugin error emotecraft-2.1-SNAPSHOT-6385565-bukkit.jar

### ISSUE THREAD

**Issue by Disguys** [KosmX/emotes#146]
The fact is that the plugin version `emotecraft-2.1-SNAPSHOT-6385565-bukkit.jar` and below leads to error that when a player presses shift in order to prevent the reproduction of an emotion, it prevents playback only for the person who used it, for players who are watching, this emotion still remains, it is corrected only by re-entering the server.

**Comment by KosmX** [comment]
The sync logic will be modified in the next snapshot.
I hope, fixed
