### ISSUE TITLE
Texture bug with HD skins when playing emotes with bend effects

### ISSUE THREAD

**Issue by DB20-official** [KosmX/emotes#147]
**Description:**
What happens is that if you have a mod that allows you to have HD skins (such as CustomSkinLoader) and have an HD skin loaded into your game, playing an emote with bend effects causes every "pixel" to rotate 90° (degrees) counter-clockwise. This is irritating when people want good-looking emotes while having them not bug out HD skins. If possible, fix the issue for those roleplayers out there! If it can't be fixed, see if there's any possible workarounds or any suggestions as to what to do. If any more problems arise, please state them.

**How to reproduce:** Load an HD skin from a skin mod. Go to your Emote Wheel, click All Emotes, and select any emote with bend effects.

**Expected behavior:** Bend Emote should play correctly without corrupting the HD skin's textures.

**Actual behavior:** Bend Emote plays correctly, but it corrupts the HD skin textures by rotating every "pixel" 90 degrees counter-clockwise.

**Emotecraft version:** v2.0.9

**Minecraft version:** 1.16.5

**Mod loader:** Fabric

**Other mods:**
_(Most shouldn't impact Emotecraft but listing them anyway in case there are known incompatibilities)_
Better Third Person (Socolio, DreenDex), Camera Overhaul (Mirsario), CustomSkinLoader (xfl03, JLChnToZ), Damage Tilt (Charles445), Dynamic FPS (juliand665), Dynamic Sound Filters (andre111), First Person Model (tr7zw), MiniHUD (masa), Mod Menu (Prospector, TerraformersMC), NotEnoughAnimations (tr7zw), Ok Zoomer (joaoh1), OptiFabric (Modmuss50, Chocohead), Physics Mod (Haubna), Presense Footsteps (Hurricanne (Ha3), Sollace), Replay Mod (CrushedPixel, johni0702), RPG-Hud (KurodaAkira), Xaero's Minimap (Xaero96), Xaero's World Map (Xaero96)

**Comment by KosmX** [comment]
It can be fixed. When I subdivided the mesh, I did not think about HD skins.

**Comment by KosmX** [comment]
bendy-lib 2.0.4 snapshot should fix the issue. (on Minecraft 1.17)
I'm working on a backport

**Comment by DB20-official** [comment]
Late update, but the bends on the latest 1.17.1 alpha build work perfectly with HD skins now. Texture bug no longer exists. Hope the 1.16 port and 1.17.1 stable release have the fix as well! Screenshot of it working with the example bend emote can be seen below:
![2021-09-18_23 57 50](https://user-images.githubusercontent.com/26073967/133915038-e139df20-6c7a-4da8-b452-8cbb4e1cb2b0.png)
