### ISSUE TITLE
Error occurred with Skin Layers 3D 

### ISSUE THREAD

**Issue by Disguys** [KosmX/emotes#168]
I installed the Emotecraft and Skin Layers 3D mod on Fabric 1.17.1, apparently because of the 3D layer the hands cannot adjust to the animation, I do not know in which exactly the problem arises.
The developer of the Skin Layers 3D mod say that you may be able to fix this, I will be very grateful if you fix this error.
Video: https://youtu.be/sd2ydCt9ugo
https://github.com/tr7zw/3d-Skin-Layers/issues/13

**Comment by jewkeZ** [comment]
Скинь пак анимаций Миляна

**Comment by KosmX** [comment]
I don't speak Russian.  

I will look at it after the modular setup is working... (player animation library)

**Comment by ToxicSilent** [comment]
@jewkeZ https://docs.google.com/document/d/1mIh0roUFZ3xiROibgymcMNu6nrD6hrXF18rTmp0SkB4/edit

**Comment by Disguys** [comment]
Developer of 3D Skin Layers fixed this, and now the 2nd layer of skin does not break when playing emotes.
Use 3D Skin Layers version 1.5.2 or above.

Video review - https://youtu.be/xeYk7IRF7RM

**Comment by DarthExekutor** [comment]
Is it possible to implement this on 1.16.5?
