### ISSUE TITLE
The emotion does not stop bukkit 2.1 snapshot

### ISSUE THREAD

**Issue by Raipus** [KosmX/emotes#178]
Greetings, it's me again. I found that the `emotecraft-for-MC1.16.5-2.1-SNAPSHOT-build.8-fabric.jar` version plugin causes a bug: when a player presses shift or moves to prevent an emotion from playing, it only prevents the emotion from playing for itself, for players who are watching, the emotion still remains, only corrected by logging back into the server.
Can you say how to fix this?

**Comment by KosmX** [comment]
Should be the same bug. Someone uses Emotecraft `2.0` on the client.  
2.0 and 2.1 are still not compatible:
I've changed how the server handles the emote stop event, to work with GeyserMC - Bedrock


(And the version checker does not work correctly in 2.0 versions)

If everyone uses `2.1-SNAPSHOT-build.8`, I'll look into it.

**Comment by Raipus** [comment]
All of these players are using version 2.1 and the problem is the same.

![image](https://user-images.githubusercontent.com/92184466/145716594-348e9f42-c342-4069-93a5-054261a8eeb9.png)

**Comment by KosmX** [comment]
It works on a fabric server, but not on Bukkit...  
The code is the same, only the platform implementation is different...

**Comment by KosmX** [comment]
I've found the bug... fix it in a few minutes.  
The bug only affects the server. Players won't need to update.

**Comment by KosmX** [comment]
The release action is running, it will be `2.1-SNAPSHOT-build.9`
