### ISSUE TITLE
Seems like github releases are behind the ones on the curseforge.

### ISSUE THREAD

**Issue by RDKRACZ** [KosmX/emotes#20]

**Comment by KosmX** [comment]
Most of the users use Curseforge and not Github...
And I forgot to upload here everything...  
I think I'll add an auto-publish to the Gradle script. then I won't forget these
(I also forget to publish on jfrog)

**Comment by KosmX** [comment]
AutoPublish is now working. I won't forget to publish to everywhere
GitHub releases
CurseForge
Modrinth
Bintray
