### ISSUE TITLE
Game crash on startup (vs MC1.18.2-2.1.1-fabric)

### ISSUE THREAD

**Issue by NovaXCIV** [KosmX/emotes#228]
![image](https://user-images.githubusercontent.com/104044556/164343624-ef10ab3f-48db-41b8-9da5-f54022343dfe.png)

**Comment by KosmX** [comment]
Please try 2.1  
If it does not work, please send a crash report.  
https://minecrafthopper.net/help/guides/getting-minecraft-crash-report/

**Comment by NovaXCIV** [comment]
Fixed. It is just incompatible with emotecraft (https://www.curseforge.com/minecraft/mc-mods/emotecraft)
