### ISSUE TITLE
[1.16.5] Latest snapshot causes mixin related misbehaviour with enchantments on ItemStack.

### ISSUE THREAD

**Issue by Colin-J-Wood** [KosmX/emotes#240]
This crash was fixed by removing your mod alone.  And yes, I did get it to happen with just Unique Enchantments Base and EmoteCraft installed.

https://pastebin.com/yFF9r8Cq

**Comment by KosmX** [comment]
Can you check if the latest **release** does cause a crash (2.1.2)?  
Please send a complete Minecraft log, not just the crash report.  
This does not contain any relevant information.

**Comment by KosmX** [comment]
There is an issue with Forge 1.16 snapshot, potentially related to your issue.  

__alpha__ builds are untested and are used for API testing and experimenting.  
Do not use those in production environment!

**Comment by NighthowlerStudios** [comment]
Understood.   I will test latest release instead tomorrow.  Please note that using the term alpha for a pure programmer's side testing feels like a misread, personally I would have used the term "pre-alpha" for such a thing and not released such a build on curseforge, so please forgive my confusion.  I keep alpha mods enabled in the launcher as some of the mods I use in my modpack never updated their status to release.

I will let you know if latest release is working or not.  (Note this account is my alt)

**Comment by Colin-J-Wood** [comment]
I can confirm latest 2.1.2 is not crashing.  Thank you for your time.  I'll keep the issue open though for your personal reference for the bug on the snapshot itself.
