### ISSUE TITLE
Crashes uppon startup. Exit Code:1

### ISSUE THREAD

**Issue by DiggiiLife** [KosmX/emotes#258]
I'm using forge 1.18.2 40.1.20 and the mod is also forge 1.18.2 but it just crashes when i start minecraft, I did make sure it was the mod causing the crash because i started minecraft without the mod and it had no problems, Ive had this kind of issue whenever i had an outdated Forge intallation, Is there any way to know the forge version it requires?

**Comment by KosmX** [comment]
It can be a compatibility issue, I can **not** tell without crash report.
Please send a crash report and reopen the issue!

**Comment by DiggiiLife** [comment]
> It can be a compatibility issue, I can **not** tell without crash report. Please send a crash report and reopen the issue!

i forgot to mention that i had other mods installed, i moved them out and its working but i dont know what mod was causing the issue becuase i have like... 30 of them (for a server). also, is there some sort of tutorial on how to add custom animations becuase im having a difficult time doing it.
