### ISSUE TITLE
Configs

### ISSUE THREAD

**Issue by Mr1rbis** [KosmX/emotes#275]
Hello, I have a question, I have a server on 1.19 and the latest version of the plugin is installed on it. The question is, should a config folder be generated in the /plugins folder? if not, how to make sure that emotions are not reset when moving

**Comment by KosmX** [comment]
The reset when moving is a client-side config.
In emotecraft config increase `stop threshold` to maximum

**Comment by Mr1rbis** [comment]
Thanks!
