### ISSUE TITLE
Help launch minecraft with Emotecraft

### ISSUE THREAD

**Issue by azarkinsss2** [KosmX/emotes#281]
I need help running a game with a 1.19 fabric mod. In addition to EmoteCraft installed:
fabric-api
litematica
malilib fabric
modmenu
OptiFabric
Optifine
simple voice chat
Without Emotecraft, minecraft starts. Please help in solving this problem.

**Comment by KosmX** [comment]
Emotecraft is incompatible with Optifine. I'll try to do something about it. but they should fix it.

Remove Optifine and install [Iris Shaders](https://irisshaders.net/)
If you miss other OF features, check out this list: https://lambdaurora.dev/optifine_alternatives/

**Comment by azarkinsss2** [comment]
Thank you
