### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by azarkinsss2** [KosmX/emotes#282]
Please help, where can I make the character move and the emotion be reproduced further?

**Comment by KosmX** [comment]
https://emotecraft.kosmx.dev/?page=creating-emotes-blender&lang=en

**Comment by azarkinsss2** [comment]
> 

No, I meant that when you use an emote and press the W button, the emote stops. How to turn it off?

**Comment by KosmX** [comment]
https://emotecraft.kosmx.dev/?page=faq&lang=en
> How can I play an emote while moving?
> In the mod options, set Stop emote at this speed threshold to the max

**Comment by azarkinsss2** [comment]
> https://emotecraft.kosmx.dev/?page=faq&lang=en
> 
> > How can I play an emote while moving?
> > In the mod options, set Stop emote at this speed threshold to the max

Thank you
