### ISSUE TITLE
[1.16.5]I can't get into minecraft

### ISSUE THREAD

**Issue by DrSigma4164** [KosmX/emotes#283]
About the title: I'm not quite sure what to call this problem, so if you don't like the title after reading the description, feel free to change it.

After I updated the "Ars Nouveau" mod, I can't enter minecraft, I don't even get to the main menu. I wrote to the author of this mod about it and he said the following:
> the log only mention an issue with the https://github.com/KosmX/emotes mod.
> It doesn't also makes much sense to be a bug with 1.25.3 and not 1.25.2 since it only added ukr translations files

In the photo below, the actual text of the error that Minecraft showed me, it says the failure occurred due to an incorrect Java Runtime configuration:
![image](https://user-images.githubusercontent.com/93322905/179394882-972767ed-d30f-4702-bbec-e2e2fb59bdc2.png)

I only got one crash log even though I tried logging in several times, so I'm not sure if the crash log describes the problem, but I'll attach it: https://pastebin.com/n5BLHHdr
These settings in the launcher: -Xms3G -Xmx8G -XX:+UseConcMarkSweepGC

**Comment by KosmX** [comment]
Ars nouveau 1.25.3 (1.16.5) is missing required assets, so it cannot load...   
The crash happened because something made a key hit with Emotecraft's keybinding before mod construction phase.

**Comment by DrSigma4164** [comment]
But in the 1.25.3 update, only the Ukrainian package was added, and nothing else, and the previous version runs fine for me.

Okay, how do I know what is pressing this key and disable it?

**Comment by KosmX** [comment]
Well, the 1.25.3 is significantly smaller.  
I checked it and it is missing assets, mixin config, and mod describer.

**Comment by KosmX** [comment]
[emotecraft-for-MC1.16.5-2.1.3-SNAPSHOT-86c8d3d-forge.zip](https://github.com/KosmX/emotes/files/9127502/emotecraft-for-MC1.16.5-2.1.3-SNAPSHOT-86c8d3d-forge.zip)
Can you try this build?
Rename the .zip to .jar, GitHub does not allow .jar extensions (even if those are only zip archives)

**Comment by DrSigma4164** [comment]
The fact is, as I already wrote, this crash log appeared only once, although I tried to start the world 5+ times. Well, actually the problem appeared after updating Ars Nouveau. So I guess I won't be able to test if it crashes until Ars Nouveau is fixed.

I tried to start minecraft 5 times. I pressed the key on the ut, which is tied to me, but there was no problem with this error, maybe when Ars Nouveau is fixed, then I will be able to test it in more detail. I am still waiting for a response from the authors of Ars Nouveau

**Comment by KosmX** [comment]
I want to look into that mod, but my Forge dev env is still loading (forge from a development perspective is garbage)

**Comment by DrSigma4164** [comment]
Scrolling glued after updating. If you delete the mod, everything works normally. This is especially noticeable in the fashion of Astral Sorcery in a book, where you need to permanently with scroll.

**Comment by KosmX** [comment]
Emotecraft does nothing with scrolling...  
You might have a very different bug.

**Comment by DrSigma4164** [comment]
I downloaded the new version, as well as the libraries: bendy-lib, playerAnimator, which you wrote about on the CurseForge page. However, minecraft does not start, I am attaching the latest.log and crashreport

https://pastebin.com/7JfHsjQ6  -  [crash-2022-08-12_18.16.43-client.txt](https://github.com/KosmX/emotes/files/9320852/crash-2022-08-12_18.16.43-client.txt)
https://pastebin.com/3pXYnfJs  -  [latest.log](https://github.com/KosmX/emotes/files/9320848/latest.log)

**Comment by KosmX** [comment]
In the logs, I see no reference to emotecraft.  

Can you somehow zip and send me the whole modpack?   
You may contact me on Discord `KosmX#7620`

**Comment by KosmX** [comment]
Maybe try without `bendy-lib`

**Comment by KosmX** [comment]
Found something!
```

Caused by: java.lang.NullPointerException
	at net.minecraftforge.fml.ModList.isLoaded(ModList.java:181) ~[?:?]
	at dev.kosmx.playerAnim.impl.forge.HelperImpl.isBendyLibPresent(HelperImpl.java:7) ~[?:?]
	at dev.kosmx.playerAnim.impl.Helper.isBendyLibPresent(Helper.java) ~[?:?]
	at dev.kosmx.playerAnim.impl.Helper.isBendEnabled(Helper.java:17) ~[?:?]
	at dev.kosmx.playerAnim.impl.IBendHelper.create(IBendHelper.java:28) ~[?:?]
	at dev.kosmx.playerAnim.impl.IBendHelper.create(IBendHelper.java:36) ~[?:?]
	at net.minecraft.client.renderer.entity.model.BipedModel.handler$zbe000$initBend(SourceFile:547) ~[?:?]
	at net.minecraft.client.renderer.entity.model.BipedModel.<init>(SourceFile:95) ~[?:?]
	at net.minecraft.client.renderer.entity.model.BipedModel.<init>(SourceFile:58) ~[?:?]
	at com.github.alexthe666.iceandfire.client.model.ModelFireDragonArmor.<init>(ModelFireDragonArmor.java:34) ~[?:2.1.10-1.16.5]
	at com.github.alexthe666.iceandfire.client.ClientProxy.<clinit>(ClientProxy.java:41) ~[?:2.1.10-1.16.5]
	at com.github.alexthe666.iceandfire.IceAndFire$$Lambda$3420/316687665.get(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.DistExecutor.safeRunForDist(DistExecutor.java:187) ~[?:?]
	at com.github.alexthe666.iceandfire.IceAndFire.<clinit>(IceAndFire.java:65) ~[?:2.1.10-1.16.5]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_51]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_51]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.<init>(FMLModContainer.java:47) ~[?:36.2]
```

**Comment by DrSigma4164** [comment]
I'm already on your server: Jonh_Smith#2115

I can download a profiler with all configs, mods, etc.

I'll try without the bendy-lib mod in a couple of minutes, finish the recipe and start already.

**Comment by KosmX** [comment]
When I try to check if a mod is present, Forge throws a `NullPointerException`...  
How am I supposed to check the mod *if* forge is so broken?!

**Comment by DrSigma4164** [comment]
Well, regarding the fact that how to check if there is a mod, I will not tell you anything, since I did not work with mods, but it is strange that there is no function that would allow you to check the presence of a mod)

And if I made any mistake, I'm sorry, my English is not good enough.

I see that you have a section with the Russian community, if you know it, then we can talk in it, if it is more convenient for you.

**Comment by KosmX** [comment]
There is a function to check other mods, it is just *broken*...   

Weirdly I've never had an issue like this with Fabric.

And your English is fine...
