### ISSUE TITLE
When using PurpurMC with Protocollib, ping is incorrect

### ISSUE THREAD

**Issue by FITFC** [KosmX/emotes#293]
When using PurpurMC 1.19.2 with Protocollib (build on 08/06/22) is having problems.

**Comment by KosmX** [comment]
Please share server logs and plugin versions.

**Comment by KosmX** [comment]
Try using 1.19 [ProtocolLib](https://www.spigotmc.org/resources/protocollib.1997/)

**Comment by KosmX** [comment]
Yes, I can see what do you say, **but you should've create a detailed issue report**...  
https://github.com/dmulloy2/ProtocolLib/issues/1828
