### ISSUE TITLE
I keep crashing on 1.19 forge

### ISSUE THREAD

**Issue by Thisguyneedshelp** [KosmX/emotes#300]
The game starts up fine for the most part and sometimes works but it usually will be me a weird message saying it cant contact this github or something, here's the logs https://mclo.gs/MSATm7B

**Comment by KosmX** [comment]
I don't see the weird message, your log appears to be incomplete.

**Comment by Thisguyneedshelp** [comment]
oh my bad, i think it mightve been cause i installed the bendy lib and stuff for 1.19, im testing now and ill lyk

**Comment by Thisguyneedshelp** [comment]
yeah that was it

**Comment by Thisguyneedshelp** [comment]
never mind it happened again here's the log https://mclo.gs/viiYu25 its just one line towardsthe bottom that says because tracker is null

**Comment by KosmX** [comment]
I think I try to access player tacking data before the server is ready.

**Comment by Thisguyneedshelp** [comment]
i see well you already helped me sorry for going for help on both i didnt think youd respond so quickly here.
