### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by ChillBrian** [KosmX/emotes#314]
**Describe the bug**
The plugin is not working on the server, it says "Server has no version of emotecraft installed, while it does

**To Reproduce**
Put the plugin in the plugin 1.19.2 paper server

**Expected behavior**
For it work ig lmao

**Minecraft version+mod loader**
 - 1.19.2 paper Server

**Mod version**: [2.2.0]

**Minecraft log __and__ crash report**:
[latest.log](https://github.com/KosmX/emotes/files/9592304/latest.log)

**Additional context**

**Comment by KosmX** [comment]
Please install ProtocolLib
