### ISSUE TITLE
Flashback/ReplayMod compatibility

### ISSUE THREAD

**Issue by KosmX** [KosmX/emotes#33]
ReplayMod/Flashback doesn't replay emotes correctly.
problem:
Mods does record the network packets but it doesn't re-register the custom channels. It will cause an invalid packet in the replay and makes the emote not working.

**To record via replaymod/flashback, use https://modrinth.com/project/eURNg52n**

**Comment by JustinSchweiger** [comment]
Do you have an approximate ETA for this? I'm working on a movie and using emotecraft would really spice things up :)

**Comment by KosmX** [comment]
I'm pretty busy with IRL things now, Probably in summer, I'll have time to fix it.

**Comment by un-simp** [comment]
Hey, Any sort of update to this? It would be a really nice feature.

**Comment by KosmX** [comment]
Nothing.
With the forge port, I made it even more difficult to support a replay-mod compatibility module. And I just forgot about this.

I don't think, I could make a perfect compatibility, but something might be possible

**Comment by KosmX** [comment]
There is a compatibility layer on **1.19.x** [fabric]:   
https://github.com/KosmX/emotes-replaymod-compat/releases

**Comment by samncg** [comment]
hi, is there an update for 1.21.1? I really want to use it with replay mod.
