### ISSUE TITLE
the server does not see the plugin

### ISSUE THREAD

**Issue by Xeventer** [KosmX/emotes#335]
server: 1.19.2 core:bukkit

when starting the server, the plugin does not work and is not displayed in the list of plugins, although others work. The mod is also not mentioned in the console, I just downloaded the file from the site and transferred it to the plugins folder, maybe I did something wrong here?

**Comment by KosmX** [comment]
Did you install protocollib?  

Also, when opening an issue, you should send logs or I can not help.
