### ISSUE TITLE
[Question] Is it possible to make it so that other clients using Emotecraft can see your emotes without having it installed server side

### ISSUE THREAD

**Issue by RaptaG** [KosmX/emotes#370]
It would be really useful

**Comment by KosmX** [comment]
Without a modded server, the clients can't share any custom information.  
Then the only option is to re-purpose some existing way of sharing information,
- chat would work, but only for limited data: maybe the animation id but nothing else.
- movement is hard to use for this. (Couldn't work in production)
- the client has no rights to do anything else.

---

Another way to approach this is to make a 3rd server to "proxy" emote information around the dedicated server.  
This has already been done but I don't have a server to host any service like this.
> I mean Emotecraft already has some API for this purpose...

If you're interested in this "hosting an emotecraft proxy" for yourself, there is already some stuff:
https://github.com/KosmX/socket-emotes-proxy

**Comment by RaptaG** [comment]
> This has already been done but I don't have a server to host any service like this.

Have you ever thought of using an Oracle Free Tier VPS? With a bit of tweaking the partition can reach up to 200GB! It's a free-for-life service which has proven to be quite reliable..

**Comment by RaptaG** [comment]
https://www.oracle.com/cloud/free/

**Comment by KosmX** [comment]
Yes, I know about that.  (https://emotes.kosmx.dev/ is hosted there)

But I don't have much support from the community if the service has to be scaled up, and implementing rate-limiters and other tools takes a lot of time what I don't have.

**Comment by RaptaG** [comment]
Would such a server require to permanently store player data? Because if so this VPS wouldn't be enough after a certain point.

**Comment by KosmX** [comment]
Storing only credentials is required (what is very little data) but the traffic can be high => a lot of users means CPU and memory is needed.

The main issue with this is __I don't have the time and money__ to implement the service.
> If you want to discuss it further, please contact me on Discord or Matrix [you can find contact info here](https://kosmx.dev/)

**Comment by RaptaG** [comment]
Alright, thank you for your quick reply! I'll consider joining your Discord where we could possibly continue the discussion
