### ISSUE TITLE
[Forge] Latest beta doesn't let the game boot

### ISSUE THREAD

**Issue by Enderteck** [KosmX/emotes#373]
**With emotecraft-for-MC1.19.2-2.2.7-b.build.48-forge.jar and Forge 43.2.8 the game doesn't start.**

**To Reproduce**:

Install emotecraft-for-MC1.19.2-2.2.7-b.build.48-forge.jar and its dependencies.

 - emotecraft-for-MC1.19.2-2.2.7-b.build.48-forge.jar
 - Forge 43.2.8
 - Client

**Minecraft log __and__ crash report**:

[latest.log](https://github.com/KosmX/emotes/files/11260733/latest.log)

```
No crash reports because the game doesn't start
```

Mods used:

  [✔] ad_astra-forge-1.19.2-1.12.6
  [✔] adaptive_performance_tweaks_core_1.19.2-6.7.0
  [✔] adaptive_performance_tweaks_gamerules_1.19.2-6.5.0
  [✔] adaptive_performance_tweaks_items_1.19.2-6.6.0
  [✔] adaptive_performance_tweaks_mods_1.19.2-6.5.2
  [✔] adaptive_performance_tweaks_player_1.19.2-6.5.0
  [✔] adaptive_performance_tweaks_spawn_1.19.2-6.7.0
  [✔] Ad-Astra-Giselle-Addon-forge-1.19.2-1.13
  [✔] adtetra-1.0.1
  [✔] AdvancementPlaques-1.19.2-1.4.7
  [✔] AllTheCompatibility-1.19.2-(v.1.9.3) 
  [✔] alltheores-2.0.2-1.19.2-43.1.3
  [✔] AnvilNeverTooExpensive-1.19-1.1
  [✔] appleskin-forge-mc1.19-2.4.2
  [✔] architectury-6.5.77-forge
  [✔] AttributeFix-Forge-1.19.2-17.2.6
  [✔] AutoRegLib-1.8.2-55
  [✔] balm-forge-1.19.2-4.5.7
  [✔] bendy-lib-forge-2.1.1
  [✔] BetterAdvancements-1.19.2-0.3.0.148
  [✔] BetterF3-4.0.0-Forge-1.19.2
  [✔] betterstats-2.2.2+1.19.2
  [✔] BetterThirdPerson-Forge-1.19-1.9.0
  [✔] biggerreactors-1.19.2-0.6.0-beta.6.1
  [✔] BiomesOPlenty-1.19.2-17.1.2.544
  [✔] blueprint-1.19.2-6.1.2
  [✔] blur-2.6.1+mc1.19.2-build.1
  [✔] Bookshelf-Forge-1.19.2-16.2.18
  [✔] BorderlessWindow-1.19.1-1.5.2
  [✔] Botania-1.19.2-438-FORGE
  [✔] BotanyPots-Forge-1.19.2-9.0.31
  [✔] BotanyTrees-Forge-1.19.2-5.0.5
  [✔] botarium-forge-1.19.2-1.8.2
  [✔] cameraoverhaul-1.0-1.19.2
  [✔] carryon-forge-1.19.2-2.0.5.10
  [✔] catalogue-1.7.0-1.19.2
  [✔] cfm-7.0.0-pre35-1.19.2
  [✔] Chargers-1.19.2-5.0.0.15
  [✔] chat_heads-0.10.8-forge-1.19.2
  [✔] cherishedworlds-forge-6.0.4+1.19.4
  [✔] ChickenChunks-1.19.2-2.9.4.97-universal
  [✔] chipped-forge-1.19.2-2.1.4
  [✔] classicbar-1.19.2-6.1.2
  [✔] clienttweaks-forge-1.19.2-8.1.1
  [✔] cloth-config-8.2.88-forge
  [✔] CodeChickenLib-1.19.2-4.3.1.481-universal
  [✔] cofh_core-1.19.2-10.2.1.40
  [✔] collective-1.19.2-6.53
  [✔] configured-2.1.1-1.19.2
  [✔] connectedglass-1.1.6-forge-mc1.19
  [✔] connectivity-1.19.2-3.4
  [✔] constructionwand-1.19.2-2.10
  [✔] Controlling-forge-1.19.2-10.0+7
  [✔] cookingforblockheads-forge-1.19.2-13.3.1
  [✔] corail_woodcutter_extension_byg-1.19.2-1.0.3
  [✔] corail_woodcutter-1.19.2-2.5.2
  [✔] craftingstation-1.19.2-6.0.1
  [✔] craftingtweaks-forge-1.19-15.1.6
  [✔] create_enchantment_industry-1.19.2-for-create-0.5.0.i-1.1.17
  [✔] create-1.19.2-0.5.0.i
  [✔] createaddition-1.19.2-20230411a
  [✔] createastracompat-1.0.1-1.19.2
  [✔] createchunkloading-1.3.0-forge
  [✔] create-stuff-additions1.19.2_v2.0.2c
  [✔] CTM-1.19.2-1.1.6+8
  [✔] Cucumber-1.19.2-6.0.6
  [✔] curios-forge-1.19.2-5.1.4.0
  [✔] CuriosQuarkOBP-1.19.2-1.2.2
  [✔] curiotiab-1.19.2-1.5.1
  [✔] Cyclic-1.19.2-1.7.14
  [✔] DarkPaintings-Forge-1.19.2-13.1.5
  [✔] Decorative Blocks-forge-1.19.2-3.0.0
  [✔] defaultoptions-forge-1.19-15.0.1
  [✔] Ding-1.19.2-Forge-1.4.0
  [✔] drawerfps-1.19.2-1.8
  [✔] dropz-forge-2.2.0+1.19.2
  [✔] dummmmmmy-1.19.2-1.7.1
  [✔] DustrialDecor-1.3.3-1.19.2
  [✔] dynamiclightsreforged-1.19.2_v1.4.0
  [✔] eatinganimation-1.19-3.2.0
  [✔] EdivadLib-1.19.2-1.2.0
  [✔] effective_fg-1.3.4
  [✔] effortlessbuilding-1.19.2-3.0
  [✔] elevatorid-1.19.2-1.8.9
  [✔] emotecraft-for-MC1.18.2-2.2.7-b.build.48-forge
  [✔] EnchantmentDescriptions-Forge-1.19.2-13.0.14
  [✔] endercrop-1.19.2-1.7.0-beta
  [✔] EnderMail-1.19.2-1.2.6
  [✔] endersdelight-1.19-1.0.2
  [✔] EnderStorage-1.19.2-2.10.1.181-universal
  [✔] energymeter-1.19.2-1.0.0
  [✔] engineersdecor-1.19.2-forge-1.3.28
  [✔] ensorcellation-1.19.2-4.2.0.14
  [✔] entity_texture_features_forge_1.19.2-4.3.3
  [✔] entityculling-forge-1.6.1-mc1.19.2
  [✔] Essential-forge_1-18-2
  [✔] everycomp-1.19.2-2.3.3
  [✔] ExperienceBugFix-1.19-1.41.2.3
  [✔] extremesoundmuffler-3.37-forge-1.19.2
  [✔] fairylights-6.0.0-1.19.2
  [✔] Fallingleaves-1.19.1-2.0.0-alpha+20221129-2000
  [✔] FarmersDelight-1.19-1.2.0
  [✔] FarmersRespite-1.19-2.0
  [✔] farmingforblockheads-forge-1.19.2-11.2.0
  [✔] findme-3.1.0-forge
  [✔] flywheel-forge-1.19.2-0.6.8.a
  [✔] FramedBlocks-6.8.3
  [✔] framedcompactdrawers-1.19-5.2.1
  [✔] freecam-forge-1.1.6+1.19
  [✔] friendsandfoes-forge-mc1.19.2-1.8.1
  [✔] ftbbackups2-forge-1.19.2-1.0.18
  [✔] ftb-dripper-1902.1.0-build.1
  [✔] ftb-essentials-1902.1.10-build.47
  [✔] ftb-library-forge-1902.3.17-build.200
  [✔] GameMenuModOption-1.19-1.18
  [✔] HammerLib-1.19.2-19.3.56
  [✔] iammusicplayer-forge-mc1.19.2-3.19.8
  [✔] Iceberg-1.19.2-forge-1.1.4
  [✔] ImmersiveEngineering-1.19.2-9.2.1-164
  [✔] inventorio-1.19-forge-1.8.7
  [✔] invhud.forge.1.19-3.4.7
  [✔] IronJetpacks-1.19.2-6.0.3
  [✔] item-filters-forge-1902.2.9-build.46
  [✔] Jade-1.19.1-forge-8.8.1
  [✔] JadeAddons-1.19.2-forge-3.4.0
  [✔] konkrete_forge_1.6.0_MC_1.19-1.19.2
  [✔] kotlinforforge-3.11.0-all
  [✔] lazydfu-1.19-1.0.2
  [✔] limitedchunks-1.19.2-2.4
  [✔] lootr-1.19-0.4.23.60
  [✔] mcjtylib-1.19-7.2.4
  [✔] mcw-paintings-1.0.4-mc1.19.2
  [✔] mcw-paths-1.0.2forge-mc1.19.2
  [✔] mcw-roofs-2.2.3-mc1.19.2forge
  [✔] mcw-windows-2.1.1-mc1.19.2forge
  [✔] Mekanism-1.19.2-10.3.8.477
  [✔] MekanismAdditions-1.19.2-10.3.8.477
  [✔] MekanismGenerators-1.19.2-10.3.8.477
  [✔] MekanismTools-1.19.2-10.3.8.477
  [✔] memoryleakfix-forge-1.17+-1.0.0
  [✔] mining_dimension-1.19.2-1.0.0
  [✔] modelfix-1.8
  [✔] moonlight-1.19.2-2.2.31-forge
  [✔] MoreMekanismProcessing-1.19.2-3.0
  [✔] MouseTweaks-forge-mc1.19-2.23
  [✔] music_player-1.19.2-2.5.1.202
  [✔] mutil-1.19.2-5.1.0
  [✔] NaturesCompass-1.19.2-1.10.0-forge
  [✔] Neat-1.19-32
  [✔] NethersDelight-1.19-3.0
  [✔] nocubes_create_compats_1.0.0_forge_1.19.2
  [✔] notenoughanimations-forge-1.6.2-mc1.19.2
  [✔] notenoughcrashes-4.2.1+1.19.2-forge
  [✔] oculus-flywheel-compat-1.19.2-0.1.8-BETA
  [✔] oculus-mc1.19.2-1.2.8a
  [✔] Oh_The_Biomes_You'll_Go-forge-1.19.2-2.0.0.13
  [✔] OreBerries-Replanted-1.19.2-0.2.1
  [✔] OreExcavation-1.11.166
  [✔] otyacraftengine-forge-mc1.19.2-3.2.0
  [✔] pamhc2crops-1.19.2-1.0.1
  [✔] pamhc2foodcore-1.19.2-1.0.0
  [✔] pamhc2foodextended-1.19.2-1.0.0
  [✔] pamhc2trees-1.19.2-1.0.1
  [✔] Patchouli-1.19.2-77
  [✔] phosphophyllite-1.19.2-0.6.0-beta.7
  [✔] physics-mod-pro-v146-forge-1.19.2
  [✔] PickUpNotifier-v4.2.4-1.19.2-Forge
  [✔] pitg-1.19.1-2.1.2
  [✔] Placebo-1.19.2-7.1.7
  [✔] player-animation-lib-forge-1.0.2
  [✔] polylib-forge-1900.0.2-build.73
  [✔] polymorph-forge-0.46.1+1.19.2
  [✔] Powah-4.0.8
  [✔] preciseblockplacing-2.0.2+1.19-forge
  [✔] Prism-1.19.1-1.0.2
  [✔] PuzzlesLib-v4.3.12-1.19.2-Forge
  [✔] Quark-3.4-397
  [✔] QuarkEngineering
  [✔] QuarkOddities-1.18
  [✔] quartz-1.19.2-0.1.0-beta.2.1
  [✔] radiantgear-forge-2.0.1+1.19.2
  [✔] radium-0.8.2
  [✔] radon-0.8.2
  [✔] rayon-forge-1.7.0+1.19.2
  [✔] ReAuth-1.19-Forge-4.0.7
  [✔] recipe-book-is-pain-0.7.1-1.19-forge
  [✔] redstone_arsenal-1.19.2-7.2.0.15
  [✔] refinedcooking-3.0.3
  [✔] refinedstorage-1.11.6
  [✔] refinedstorageaddons-0.9.0
  [✔] refstoragefluxified-1.16.5-1.0.1
  [✔] REIPluginCompatibilities-forge-9.0.48
  [✔] resourcefulconfig-forge-1.19.2-1.0.20
  [✔] resourcefullib-forge-1.19.2-1.1.24
  [✔] rftoolsbase-1.19-4.1.7
  [✔] rftoolsbuilder-1.19-5.2.6
  [✔] rftoolsdim-1.19.2-9.1.5
  [✔] rftoolsstorage-1.19-4.1.2
  [✔] RoughlyEnoughItems-9.1.595
  [✔] rubidium_extras-1.19.2_v1.3.2
  [✔] rubidium-0.6.2a
  [✔] rubidium-extra-0.4.17+mc1.19.2-build.71
  [✔] sebastrnlib-2.0.2
  [✔] Smooth Swapping-1.19.2-1.0.2
  [✔] smoothboot(reloaded)-mc1.19.2-0.0.2
  [✔] smoothchunk-1.19.1-2.0
  [✘] SolarFluxReborn-1.19.2-19.3.10.jar (disabled)
  [✔] sophisticatedbackpacks-1.19.2-3.18.44.815
  [✔] sophisticatedcore-1.19.2-0.5.49.245
  [✔] sophisticatedstorage-1.19.2-0.6.26.325
  [✔] soundphysics-forge-1.19.2-1.0.18
  [✔] spark-1.10.34-forge
  [✔] spelunkery-1.19.2-0.2.0-forge
  [✔] Steam_Rails-1.19.2-1.1.1
  [✔] StorageDrawers-1.19-11.1.2
  [✔] supermartijn642configlib-1.1.6b-forge-mc1.19
  [✔] supermartijn642corelib-1.1.7-forge-mc1.19
  [✔] supplementaries-1.19.2-2.3.4
  [✔] suppsquared-1.19.2-1.0.14
  [✔] TerraBlender-forge-1.19.2-2.0.1.136
  [✔] tesseract-1.0.30a-forge-mc1.19
  [✔] tetra-1.19.2-5.2.1
  [✔] tetrasdelight-1.19.2-1
  [✔] TextruesRubidiumOptions-1.0.4-mc1.19.2
  [✔] thermal_cultivation-1.19.2-10.2.0.17
  [✔] thermal_dynamics-1.19.2-10.2.1b.14
  [✔] thermal_expansion-1.19.2-10.2.0.21
  [✔] thermal_foundation-1.19.2-10.2.0.47
  [✔] thermal_innovation-1.19.2-10.2.0.18
  [✔] thermal_integration-1.19.2-10.2.0.17
  [✔] thermal_locomotion-1.19.2-10.2.0.14
  [✔] tia-1.19.2-1.0-forge
  [✔] time-in-a-bottle-3.0.1-mc1.19
  [✔] Tips-Forge-1.19.2-8.0.27
  [✔] ToastControl-1.19.2-7.0.0
  [✔] torchmaster-19.2.0
  [✔] trashcans-1.0.17a-forge-mc1.19
  [✔] twilightforest-1.19.2-4.2.1518-universal
  [✔] u_team_core-1.19.2-4.4.3.236
  [✔] upgradedcore-1.19.2-4.1.0.1-release
  [✔] upgradednetherite_items-1.19.2-4.1.0.1-release
  [✔] upgradednetherite_ultimate-1.19.2-4.1.0.3-release
  [✔] upgradednetherite-1.19.2-5.1.0.6-release
  [✔] v_slab_compat-1.19.2-1.4
  [✔] VisualWorkbench-v4.2.4-1.19.2-Forge
  [✔] voicechat-forge-1.19.2-2.4.4
  [✔] WaterStrainer-1.19-14.1.1
  [✔] waystones-forge-1.19.2-11.3.1
  [✔] worldedit-mod-7.2.12
  [✔] Xaeros_Minimap_23.4.0_Forge_1.19.1
  [✔] XaerosWorldMap_1.30.0_Forge_1.19.1
  [✔] xnet-1.19-5.1.4
  [✔] YungsApi-1.19.2-Forge-3.8.9
  [✔] YungsBetterDesertTemples-1.19.2-Forge-2.2.2
  [✔] YungsBetterDungeons-1.19.2-Forge-3.2.2
  [✔] YungsBetterMineshafts-1.19.2-Forge-3.2.0
  [✔] YungsBetterNetherFortresses-1.19.2-Forge-1.0.5
  [✔] YungsBetterOceanMonuments-1.19.2-Forge-2.1.0
  [✔] YungsBetterStrongholds-1.19.2-Forge-3.2.0
  [✔] YungsBetterWitchHuts-1.19.2-Forge-2.1.0

**Comment by KosmX** [comment]
Please use 1.19.2 version of Emotecraft.

**Comment by KosmX** [comment]
`[✔] emotecraft-for-MC1.18.2-2.2.7-b.build.48-forge` is not 1.19.2
