### ISSUE TITLE
Neutral creatures stop attacking

### ISSUE THREAD

**Issue by s-mb07** [KosmX/emotes#377]
Neutral creatures made aggressive stop attacking when you play an animation ( 1.19.2 )
![test](https://user-images.githubusercontent.com/132605105/236288265-e463877c-f7d6-4498-95b1-c0f7b51a6e86.png)
nimation

**Comment by KosmX** [comment]
I don't understand what you want.

**Comment by s-mb07** [comment]
I create a mod on boxing so that when I click on the R key the player plays an animation of where he protects himself but when he plays the animation it's like he's invisible to the entities around and for example during a fight against an entity that normally is neutral (aggressive only if the player hits it), when I play the animation the entity stops to attack me. I tested with aggressive entities like zombies and when I play the animation it's as if it doesn't see at all and starts attacking me again after the animation.

**Comment by KosmX** [comment]
It doesn't seem to be a bug with Emotecraft.  
Normally Emotecraft doesn't stop anything from attacking the player, you do that.  

> You shouldn't stop entities from attacking, that way they will forget their target. You should remove the damage they do.
