### ISSUE TITLE
permission system

### ISSUE THREAD

**Issue by chouuul** [KosmX/emotes#387]
I only want to know if there is an addon or a permission system for 1.16.5

**Comment by KosmX** [comment]
I'm not aware of any addon doing that.

**Comment by chouuul** [comment]
I wanted to make an emote pack for my serveur when they spent 5hours of time they can do an emote.

Not possible then ?

**Comment by KosmX** [comment]
There is an API that you can use to write custom plugins. (if you know plugin development)

**Comment by chouuul** [comment]
Which api ?

**Comment by KosmX** [comment]
https://github.com/KosmX/emotes/tree/dev/emotesAPI/src/main/java/io/github/kosmx/emotes/api/events/server


In emotecraft (both mod and plugin version) there are some events that you can use to limit/control emote use.
