### ISSUE TITLE
LAN world owner doesn't see other players emotes 

### ISSUE THREAD

**Issue by BoBkiNN** [KosmX/emotes#396]
**Describe the bug**
Integrated server send emote from owner but owner doesn't see emotes from connected players

**To Reproduce**
1. Install mod to owner and player that will connect
2. Open world to LAN
3. Make another player join you world
4. Make another player play emote and you wont see it

**Expected behavior**
Owner will see emotes from other players

**Minecraft version+mod loader**
 - Version: `1.19.4`
 - Modded: `Fabric 0.14.21`
 - Integrated server

**Mod version**: `2.2.7-b.build.48`

**Minecraft log __and__ crash report**:
No errors

**Additional context**
\-

**Comment by KosmX** [comment]
Please provide logs and information about clients.

**Comment by BoBkiNN** [comment]
Tested again, no bug was found
