### ISSUE TITLE
The menu for selecting emotes is hard-coded to the player's camera.

### ISSUE THREAD

**Issue by DearFox** [KosmX/emotes#398]
**Describe the bug**
This incompatibility appeared with the FreeCam mod (Modrinth Edition)
In freecam mode, pressing the key to open the emote wheel (B by default) does nothing.
I created a bug report for the FreeCam mod: https://github.com/hashalite/Freecam/issues/97
But the mod developer said that the problem is on your side.

**To Reproduce**
1. install Freecam (Modrinth Edition)
2. enter the world
3. enter free camera mode
4. try to open the choice of emotions

**Expected Behavior**
in the free camera mode of this mod, you can open the emotion selection wheel.

**Minecraft version+mod loader**
 - Version: in theory, any version that supports these two mods (tested on 1.20.1 fabric)
 - Modded: emotecraft-for-MC1.20.1-2.2.7-a.build.49-fabric ; freecam-fabric-modrinth-1.2.0+1.20
 - Client

**Mod version**: 2.2.7-a.build.49-fabric

**Minecraft log __and__ crash report**:
does not throw errors in the console (I did not notice)

**Additional context**
by hashalite (developer of the Freecam mod (Modrinth Edition)) :
> The dev has a hard-coded check that ensures the camera entity is the player before opening the menu. There is not much I can do on my end, they would have to implement their own workaround. I suggest making an issue here: https://github.com/KosmX/emotes

> Conflicting code:
> ![image](https://github.com/KosmX/emotes/assets/59219907/f37655c3-b1fd-40b2-aa60-91d8150ec015)

**Comment by KosmX** [comment]
This check is mainly to stop people from emoting when they don't control their bodies (spectating something for example).  
But I'll add an override config for this case.

**Comment by DearFox** [comment]
> This check is mainly to stop people from emoting when they don't control their bodies (spectating something for example). But I'll add an override config for this case.

By the way, emotes to which hotkeys are assigned still work.

**Comment by KosmX** [comment]
Should be fixed by https://github.com/KosmX/emotes/commit/76b60898b958aef1a95551d418ae824b1aad2847

**Comment by KosmX** [comment]
https://github.com/KosmX/emotes/releases/tag/2.2.7-b.build.50
