### ISSUE TITLE
the plugin does not start

### ISSUE THREAD

**Issue by L1nuxc** [KosmX/emotes#410]
I downloaded the plugin for 1.20.1 from both github and other sites, but it doesn't work

version 1.20.1 Paper
![image](https://github.com/KosmX/emotes/assets/141755972/54e9d0d7-1062-4a09-a0cd-7012e0450bc8)
![image](https://github.com/KosmX/emotes/assets/141755972/bd9bcf9b-0e8e-433d-8792-513680f69e94)

**Comment by KosmX** [comment]
Well, just do what it says: Install ProtocolLib
