### ISSUE TITLE
Error occurred with [ETF] Entity Texture Features (solved)

### ISSUE THREAD

**Issue by Diclo** [KosmX/emotes#428]
**Describe the bug**
the second layer does not adjust a the animations

**Minecraft version+mod loader**
 - Version: 1.20.1
 - Modded: Quilt 0.20.2
 - Client/Server

**Mod version**
emotecraft: 2.2.7-b.build.50
3dskin: v1.5.4-mc1.20.1
entity_texture_features_fabric_1.20.1-4.6.1

**Additional context**
[https://youtu.be/qS8YTKryCds](url)

Solution:
It is fixed by changing the ETF settings / player skin settings / 3D skin layers mod path: OFF

**Comment by Baguhan-p** [comment]
Help me, it doesn't work.
*ETF settings / player skin settings / 3D skin layers mod path: OFF*

**Comment by Diclo** [comment]
> Help me, it doesn't work. _ETF settings / player skin settings / 3D skin layers mod path: OFF_

Use this version of 3Dskin: v1.5.4-mc1.20.1
and 
Maybe some extra mod is adding extra layers, for example, Essentials causes that issue with boots, etc. If I'm not familiar with a solution...

Because, yes, at least when updating the 3Dskin to a higher version, it gets damaged again.
