### ISSUE TITLE
1.19.2 issue

### ISSUE THREAD

**Issue by AlienLoser** [KosmX/emotes#439]
less of an issue and more a general question, when i press the B key to open the emote wheel, i dont get any emotes despite having them in my emote folder, instead, just the message **_Action wheel has no active page!_**
any way to fix this?

**Comment by KosmX** [comment]
Please share logs, and `.minecraft/config/emotecraft.json`

**Comment by AlienLoser** [comment]
not sure how to share logs, however here's the. json file and an image of what im getting
![07e3c38838fc0e74db9a8131d0036eff](https://github.com/KosmX/emotes/assets/117137863/fcd5bae3-4d56-4166-b644-87e6b6192737)


{
  "config_version": 4,
  "loadbuiltin": true,
  "quark": false,
  "dark": false,
  "oldChooseWheel": false,
  "perspective": true,
  "default3rdPersonFront": false,
  "showicon": true,
  "enableNSFW": false,
  "debug": true,
  "validate": false,
  "validationThreshold": 8.0,
  "emotesFolderOnLogicalServer": false,
  "emotesDirectory": "emotes",
  "autoFixEmoteStop": true,
  "alwaysValidateEmote": false,
  "playersafety": true,
  "stopthreshold": 0.04,
  "yratio": 0.75,
  "showHiddenConfig": false,
  "neverRemoveBadIcon": false,
  "exportBuiltin": false,
  "hideWarning": false,
  "fastmenu": {},
  "keys": {}
}

**Comment by KosmX** [comment]
`Action wheel has no active page!` does not belong to Emotecraft, this appears to be something else.  
[How-to get logs](https://emotes.kosmx.dev/guide/logs)

**Comment by AlienLoser** [comment]
i figured it out, apologies
