### ISSUE TITLE
Incompat with Kelvin's Better Player Animations (Port) Mod

### ISSUE THREAD

**Issue by RockRocking** [KosmX/emotes#450]
Having [Kelvin's Better Player Animations(Port)](https://modrinth.com/mod/kelvins-better-player-animations-(port)/versions?l=fabric&g=1.20.1) mod and Emotecraft installed together messes up the animations when doing emotes.  The emotes either don't do anything or the animations are messed up.  I'm not sure if the issue is caused by this mod, the other mod, or if it's simply too difficult to make them compatible.  

 - Version: 1.20.1
 - Fabric 0.15.3
 - Client

Additional context:
Kelvin's Better Player Animator mod also depends on your playerAnimator library.

**Comment by dima-dencep** [comment]
Not a emotecraft issue
