### ISSUE TITLE
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors

### ISSUE THREAD

**Issue by ashleq** [KosmX/emotes#454]
Game crashes upon launch on fabric
![image](https://github.com/KosmX/emotes/assets/157563206/31b818e8-281a-47c8-ac10-44bfbbc4d574)

**Minecraft version+mod loader**
 - Version: 1.20.4
 - Modded: Fabric 0.15.6
 - Client

**Mod version**: emotecraft-for-MC1.20.1-2.2.7-b.build.50-fabric.jar

**Minecraft log __and__ crash report**:

log here
[latest.log](https://github.com/KosmX/emotes/files/14033346/latest.log)

crash report here
[crash-2024-01-24_12.59.04-client.txt](https://github.com/KosmX/emotes/files/14033331/crash-2024-01-24_12.59.04-client.txt)

**Additional context**
Mods installed:
![image](https://github.com/KosmX/emotes/assets/157563206/73f87790-2e2d-441e-9d6e-8e744af931be)

**Comment by KosmX** [comment]
There is no 1.20.4 version for Emotecraft yet. I'm working on it

**Comment by ashleq** [comment]
Ah okay, my bad! Thanks for the help!
