### ISSUE TITLE
bones do not bend

### ISSUE THREAD

**Issue by TvaryTheKotik** [KosmX/emotes#457]
**bones do not bend**

![2024-02-0916-42-59-ezgif com-video-to-gif-converter](https://github.com/KosmX/emotes/assets/159548819/f5d0ad3a-7218-4659-941e-1a4e62887730)

**Comment by TvaryTheKotik** [comment]
> and there are other animations in which the bones do not bend, but all friends see with bent bones

**Comment by KosmX** [comment]
install bendy-lib

**Comment by TvaryTheKotik** [comment]
not working

**Comment by KosmX** [comment]
I don't have a crystal ball of remote debugging neither did I hack your computer. I don't know what are you trying to do.  

Please share some logs!

**Comment by SoulxluoS** [comment]
Perhaps the problem is with Sodium(and Iris). Starting from version 0.5.5(1.6.14), it uses a custom EntityRender. Which prevents bendy-lib from working correctly
