### ISSUE TITLE
EmoteCraft Plugin

### ISSUE THREAD

**Issue by isArkaDarkTime** [KosmX/emotes#480]
Hello! Please update the EmoteCraft plugin to new versions, we really need it!

**Comment by lxkochevnikxl** [comment]
> Привет! Пожалуйста, обновите плагин EmoteCraft до новых версий, он нам очень нужен!

I support it fully, we really need emotrcraft, please fix this mod, it still does not work correctly on version sodium-fabric-0.5.8+mc1.20.1. there is no bending of the limbs =( please, please fix it.
