### ISSUE TITLE
Update 1.21

### ISSUE THREAD

**Issue by Salmon-in-a-bucket** [KosmX/emotes#489]
Update 1.21

**Comment by KosmX** [comment]
I'll, but I want to finish BSc first (one more day)

**Comment by ComboGame** [comment]
update please

**Comment by SfortzaPhantom** [comment]
> update please

WDWIWBD

**Comment by KeiBoogie** [comment]
Pls update

**Comment by GodlyFirecracker** [comment]
will  it be on forge???

**Comment by dima-dencep** [comment]
NeoForge/Fabric only
@GodlyFirecracker

**Comment by GodlyFirecracker** [comment]
ok,but can i make a port to 1.21 forge???

**Comment by dima-dencep** [comment]
Ask KosmX

**Comment by GodlyFirecracker** [comment]
i think they allow me to port 1.21 forge,but i may only do on the most modded version only,otherwise that version will support NeoForge/Fabric only,but it will be unofficially supported,and 1.22 and above never

**Comment by KosmX** [comment]
I'll port it to NeoForge and Fabric 1.21 soon
Most mods will support NeoForge, i don't know why you want forge.

But if you port it, i can officially support it

**Comment by ComboGame** [comment]
Update to 1.21 for paper bukkit purpur

**Comment by SfortzaPhantom** [comment]
> Update to 1.21 for paper bukkit purpur

Stop being annoying and asking to update the mod to your version - devs have their own lives too.

**Comment by Auriny** [comment]
> Update to 1.21 for paper bukkit purpur

кринжанул

**Comment by mihalera** [comment]
Теперь я кринжанул

**Comment by Riflusso** [comment]
Hi, @TheMek0 made port 1.21 with the new networking system from 1.20.5, you can have a look at it [there](https://github.com/TheMek0/NoEmotecraft). I think with these fixes it'll be easier for you to port

**Comment by papamaionise** [comment]
I just hope you don't abandon the mod there's nothing like it I dont care even if it takes months updating

**Comment by MrVolli** [comment]
the main thing is for the mod to live differently, half of the server community falls into a deep depression

**Comment by dima-dencep** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/emotecraft/files/5920392
https://legacy.curseforge.com/minecraft/mc-mods/emotecraft-forge/files/5920393
