### ISSUE TITLE
Epic FIght

### ISSUE THREAD

**Issue by OneWorldStudio** [KosmX/emotes#502]
Hello, plz add support epicfight

**Comment by DoorsThingy** [comment]
What happens if you use epic fight with emotecraft?

**Comment by OneWorldStudio** [comment]
> What happens if you use epic fight with emotecraft?

There will be no animation

**Comment by OneWorldStudio** [comment]
Other options are so-so, especially disabling EpicFight animation, in non-combat

**Comment by dima-dencep** [comment]
Not a emotecraft issue

**Comment by DoorsThingy** [comment]
I believe that this is an Epic Fight issue, like what dima-dencep has said. This is a bug caused by that mod and the only fix is to: A. Fork the project and attempt to solve the issue on your own. B. just disable the mod or ignore the bug completely.
