### ISSUE TITLE
Emotes are not loading if the folder is a symbolic link

### ISSUE THREAD

**Issue by Diclo** [KosmX/emotes#504]
**Describe the bug**
When starting the game with the latest versions of Emotecraft, it does not load the emotes from the folder.
![imagen](https://github.com/user-attachments/assets/421c8231-1fb3-4533-8f5d-3bdbe5b296c9)

**To Reproduce**
1. Download any of the versions listed below.
2. Start the game, enter either a server or a singleplayer world, and open the emote wheel.

**Expected behavior**
![imagen](https://github.com/user-attachments/assets/1247fa32-2230-4a94-be44-1e03f4ff10f4)

**Minecraft version+mod loader**
 - Version: 1.21.1
 - Modloder: Fabric 0.16.9
 - Client/Server

**Mod version**: [e.g. 2.1.3-fabric]
emotecraft-for-MC1.21.1-2.4.2-b.build.55
emotecraft-for-MC1.21.1-2.4.2-b.build.56
emotecraft-for-MC1.21.1-2.4.3-b.build.57
emotecraft-for-MC1.21.1-2.4.3-b.build.58

**Minecraft log __and__ crash report**:
https://pastebin.com/FMUxmh4N

**Additional context**
emotecraft-for-MC1.21.1-2.4.1-b.build.53
it's work

**Comment by Diclo** [comment]
Sorry, the emotes cannot be read if the folder is a symbolic link. I had the emotes folder for different instances in PrismLauncher pointing to the same emotes folder to avoid redundancy, but now it doesn't work. Do you know if this can be fixed, or are there no plans to address it?

My problem isn't serious, and if it can't be resolved, I'll just copy the emotes folder, and that's it.

**Comment by dima-dencep** [comment]
Emotectaft is in beta so I'm experimenting... Thanks for telling me!

I'll try to resolve it

**Comment by MorriganNarukami** [comment]
Same thing is happening with me. However, for me it doesn't even says it's invalid
Instead it just not detect anything like the folder is empty
![image](https://github.com/user-attachments/assets/e65623a5-081d-4071-9019-a0dd7f70571d)

I'm with Essentials installed, so maybe there is some type of conflict. But I tried to search about it and didn't found anything

**Comment by dima-dencep** [comment]
> emotes cannot be read if the folder is a symbolic link

**Comment by Riflusso** [comment]
Nope, that's not fixed at build 60
![2024-11-30_01 24 25](https://github.com/user-attachments/assets/424c7e41-0c82-4c34-99a9-b7cdb8cc7831)
