### ISSUE TITLE
[1.21.1 Neoforge] Emotecraft require a version of Playeranimator that dosn't exist

### ISSUE THREAD

**Issue by SkyRunner55** [KosmX/emotes#506]
Emotecraft require version of playeranimator that dosn't exist on playeranimator download page
alpha 1 is the latest version we can have on neoforge (and fabric)

![image](https://github.com/user-attachments/assets/ba478590-515a-4dde-b91e-011e6b65cf02)

**To reproduce:**
Just start the game

**Minecraft version+mod loader**
 - 1.21.1
 - Neoforge

**Mod version**: 
emotecraft-for-MC1.21.1-2.4.4-neoforge

**Comment by dima-dencep** [comment]
skill issue

**Comment by dima-dencep** [comment]
![image](https://github.com/user-attachments/assets/25aebf11-e498-47a7-9f2b-b3ee561d3fb8)

**Comment by SkyRunner55** [comment]
well, this dosn't solve anything but ok...

**Comment by dima-dencep** [comment]
It's not, you just have a skill issues

**Comment by SkyRunner55** [comment]
welp english is not my native language, so i didn't know that word meant (this is include with) so yeah
first time i saw it
