### ISSUE TITLE
[1.21.1 Neoforge] Custom emote not loading

### ISSUE THREAD

**Issue by SkyRunner55** [KosmX/emotes#507]
Custom emotes are not loading (this was also tested with a fresh modpack with only emotecraft & player animation)

**To Reproduce:**
1. Get some emotes from internet (and put them into the emotes folder)
2. Start the game
3. Notice that there is nothing beside default emote

**Expected behavior**
Was expecting my emotes to show off

**Minecraft version+mod loader**
 - Version: 1.21.1
 - Modded: Neoforge

**Mod version**:
emotecraft-for-MC1.21.1-2.4.4-b.build.60-neoforge

also maybe in the emotecraft-for-MC1.21.1-2.4.4-neoforge
i can't tell since it require a [playeranimator version that dosn't exist](https://github.com/KosmX/emotes/issues/506)

![Capture d'écran 2024-12-11 143536](https://github.com/user-attachments/assets/3758a614-44d0-4e68-9732-30d979dc57e7)
![Capture d'écran 2024-12-11 143632](https://github.com/user-attachments/assets/cc9ca416-fa1b-4a5c-bd7d-c76cff340c4c)

**Comment by dima-dencep** [comment]
skill issue
