### ISSUE TITLE
CAN YOU PLEASE ADD MORE SLOTS 

### ISSUE THREAD

**Issue by qpiestn** [KosmX/emotes#65]
PLEASE ADD MORE SLOTS BECAUSE THERE ARE MANY BEST EMOTES IT WILL BE FINE IF THERE ARE NO TEXTURES FOR SLOT 
I WILL ADJUST BUT PLEASE IMPLEMENT THE FEATURE THAT THE SLOTS WE TYPE IT COMES WITH THAT QUANTITY ITS HARD
BUT I NEED IT.

**Comment by KosmX** [comment]
I'm thinking to add multiple pages with the same layout.
